name: CI

on: [push, pull_request]

env:
  SRB_SKIP_GEM_RBIS: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3"]
    name: Test Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bin/rspec

  lint-and-docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Lint & Docs
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Validate default config
        run: |
          bin/rubocop --config config/default.yml config -r rubocop-yjit
      - name: Lint Ruby files
        run: bin/rubocop
      - name: Verify documentation is up to date
        run: bundle exec rake generate_cops_documentation
